# Generated by Django 4.2.5 on 2023-10-31 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_shoppingcart_recipe_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientamount',
            name='unique_count',
        ),
    ]
