# Generated by Django 4.2.5 on 2023-10-31 22:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_ingredientamount_unique_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Минимум 1 минута'), django.core.validators.MaxValueValidator(180, 'Максимум 3 часа')], verbose_name='Время приготовления в минутах'),
        ),
    ]
